version: '3'
services:
    
    app:
        container_name: ngeebe
        restart: always
        build: .
        ports:
            - '8081:8081'
        links: 
            - mongo

    mongo:
        container_name: ngee
        image: mongo:4.2
        ports:
            - '27017:27017'